CUSTOM_MATRIX = lite
ANALOG_DRIVER_REQUIRED = yes
SRC += hallscan/hallscan.c

CONSOLE_ENABLE = yes
KEYBOARD_STRING_ENABLE = yes
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE = yes
CAPS_WORD_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
MOUSE_ENABLE = yes
